remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Testing Process Guide
description: Internal accessibility testing process guide
defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"